# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2

builds:
  - id: gotestchunk
    main: ./cmd/gotestchunk
    env:
      - CGO_ENABLED=0
      - GOPROXY=https://proxy.golang.org,direct
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - release

universal_binaries:
  - replace: true
    ids:
      - gotestchunk

archives:
  - format: binary
