name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Initialize Hermit
      run: |
        ./bin/hermit env -r >> $GITHUB_ENV

    - name: Run tests
      run: |
        # Run tests in parallel using go test directly
        go test -v ./... -count=1

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
