name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: cashapp/activate-hermit@v1
      with:
        cache: "true"

    - name: Run tests
      run: |
        # Run tests in parallel using go test directly
        go test -v -count=1 -json ./... | gotestsum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        install-mode: none
